BOARD_TAG = uno
ARDUINO_PORT = /dev/ttyACM0

ARDUINO_LIBS = SPI

# AVRDUDE_ARD_PROGRAMMER = stk500v1
ARDUINO_DIR = /usr/share/arduino

F_CPU = 16000000L

include /usr/share/arduino/Arduino.mk # This is where arduino-mk installed
