BOARD_TAG    = atmega328 # Here goes your board type, e.g. : uno
ARDUINO_PORT = /dev/ttyUSB0 # Change to your own tty interface

SOURCES = main_.ino

ARDUINO_LIBS = Servo LiquidCrystal Time DS1302RTC # The libs needed by your sketchbook

AVRDUDE_ARD_PROGRAMMER = stk500v1

F_CPU = 16000000L

include /usr/share/arduino/Arduino.mk # This is where arduino-mk installed
